### PR TITLE
Fixed parameters and storage settings format in `ApiRepoUpdateSlice`

### LINKED ISSUE #39: NPE on repo update
When trying to update or create repo via dashboard, management API throws NPE and returns 500 status:
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(String)" because "repo" is null
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(String)" because "repo" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(String)" because "repo" is null
	at com.artipie.management.api.ApiRepoUpdateSlice.lambda$response$2(ApiRepoUpdateSlice.java:118)
	... 4 more
```

Artipie version is `v0.20`

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #39
There were 2 problems in `ApiRepoUpdateSlice`
1) parameters separator was expected to be `;` instead of `&`
2) storage settings were always expected to be yaml, but there also can be string for `default` value

### CODE REVIEW

File: src/main/java/com/artipie/management/api/ApiRepoUpdateSlice.java [hunk 1]
```diff
@@ -157,7 +161,7 @@ public Response response(final String line,
      */
     private static String value(final String payload, final String name) {
         final int start = payload.indexOf(String.format("%s=", name)) + name.length() + 1;
-        int end = payload.indexOf(';', start);
+        int end = payload.indexOf('&', start);
```
Comment (g4s8) [inline src/main/java/com/artipie/management/api/ApiRepoUpdateSlice.java:164]: I think we need to document this cher in method javadoc

**Review by g4s8 — CHANGES_REQUESTED** [review]
@olenagerasimova just one comment

**Comment by olenagerasimova** [comment]
@g4s8 thanks, extended javadoc

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks
