### PR TITLE
#14 - extracted interface from Cookies

### LINKED ISSUE #14: Permission in ApiAuthSlice
`ApiAuthSlice` is broken as we create `Permission.ByName` with unrecognized action `api` inside it. We should use another ctor (from `Permissions` and `Action`) of `Permission.ByName` there and add test for this slice.

### PR DESCRIPTION
**Pull request by olenagerasimova**
Closes #14 
Extracted interface from `Cookies` and fixed `ApiAuthSlice` to use `All` instead of `Any` permissions.

### CODE REVIEW

File: src/main/java/com/artipie/management/api/Cookies.java [hunk 1]
```diff
@@ -24,114 +24,63 @@
...
-
-    /**
-     * Ctor.
-     *
-     * @param headers Headers.
-     */
-    public Cookies(final Iterable<Map.Entry<String, String>> headers) {
-        this.headers = headers;
-    }
+public interface Cookies {
```
Comment (olegmoz) [inline src/main/java/com/artipie/management/api/Cookies.java:34]: @olenagerasimova this interface looks surprisingly similar to `AuthScheme` that was added to HTTP module. Maybe it makes sense to use it here?

File: src/main/java/com/artipie/management/api/FromEnv.java [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+import java.util.Map;
+import java.util.Optional;
+import javax.crypto.Cipher;
+import org.apache.commons.codec.DecoderException;
+import org.apache.commons.codec.binary.Hex;
+
+/**
+ * API request cookies.
+ *
+ * @since 0.1
```
Comment (olegmoz) [inline src/main/java/com/artipie/management/api/FromEnv.java:48]: @olenagerasimova `@since` tag value is wrong here

File: src/main/java/com/artipie/management/api/FromEnv.java [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+ */
+public final class FromEnv implements Cookies {
```
Comment (olegmoz) [inline src/main/java/com/artipie/management/api/FromEnv.java:50]: @olenagerasimova I'd suggest to add "Cookies" word to class name. Right now it is totally unclear what is `FromEnv` when one see this class usage

**Review by olegmoz — CHANGES_REQUESTED** [review]
@olenagerasimova thanks, please see the comments

File: src/main/java/com/artipie/management/api/Cookies.java (hunk 1 above)
Comment (olenagerasimova) [reply src/main/java/com/artipie/management/api/Cookies.java:34]: @olegmoz thanks, I think it's a good idea. But I'll need `AuthScheme.Fake` implementation for the test. Let me submit corresponding PR in `http` and use `AuthScheme` here

**Comment by olenagerasimova** [comment]
@olegmoz thanks, corrected

File: src/main/java/com/artipie/management/api/ApiAuthSlice.java [hunk 4]
```diff
@@ -60,28 +64,28 @@
...
-    private final Cookies cookies;
+    private final AuthScheme scheme;
 
     /**
      * Ctor.
      * @param auth Authentication
      * @param perms Permissions
      * @param origin Origin slice
-     * @param cookies Cookies
+     * @param scheme Cookies
```
Comment (olegmoz) [inline src/main/java/com/artipie/management/api/ApiAuthSlice.java:76]: @olenagerasimova it seems that JavaDoc should be corrected as well

**Review by olegmoz — CHANGES_REQUESTED** [review]
@olenagerasimova thanks, please see one minor comment

**Comment by olenagerasimova** [comment]
@olegmoz thanks, corrected

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, merging
